version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    #volumes:
    #  - ./html:/usr/share/nginx/html:ro

  db:
    image: mysql:latest
    #volumes:
    #  - ./html:/usr/share/nginx/html:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: B2C6A
      MYSQL_USER: username
      MYSQL_PASSWORD: password

#volumes:
#  db-data:
